### ISSUE TITLE
Fix flap lever animation

### ISSUE THREAD

**Issue by gilbertohasnofb** [HHS81/c182#33]
After https://github.com/HHS81/c182/issues/26#event-519605842 has been implemented, the lever must be repositioned and its animation must be redone (it should move a little bit sideways after each notch).

**Comment by HHS81** [comment]
ah, I didn't know,

**Comment by gilbertohasnofb** [comment]
Maybe take a look on what onox did on the c172p: https://github.com/Juanvvc/c172p-detailed/commit/fb9a37c3187a1472c871ce9ff61ee043cfc12ef1

**Comment by HHS81** [comment]
should be fixed

**Comment by gilbertohasnofb** [comment]
Heiko, I just checked it and there are some problems still:

- I think the positions of the main lever for each notch can be slightly better placed (e.g. the 10 degrees is a bit too down I think)
- the lever is instantaneously moving from notch to notch, while in the c172p it smoothly moves. Look also how in the c172p it moves sideways before moving down/up.

**Comment by HHS81** [comment]
-the "smooth" move is somewhere burried in the c172p-files, where I can't find it. Anyway, how smooth or instantaneously the flaps lever is moving depends on your hand and force you use in RL. Really something minor for me right now....That can come later.
-they used the translate animation for up and down, but it seems the animation should be a rotate animation for lever and indicator according some  videos on youtube- so I changed it back, but kept the translate sidewards of the lever
-the flap lever in reality is a bit tilted, so I changed this to it

Push comes right now

**Comment by gilbertohasnofb** [comment]
- I don't think the smooth movement is buried in the c172p files, I think it's done only in in that xml file. I can ask onox how he did it if you want. Personally I think it looks much better than the teleporting, but it's a small thing of course. I can try having a look on it later on
- yes, the flap lever does rotate but I think the radius of the rotation is comparative large, so probably a translation is a fair approximation I suppose. See: http://airfactsjournal.com/files/2014/03/AF-flap-switch-feature.jpg
- are you sure the flap switch is twisted like that? The 172 one is certainly not: https://camo.githubusercontent.com/367ce1bb51c40097cab30ffa71426452054abc02/687474703a2f2f7777772e666c796c7061732e636f6d2f4e353331344b25323070616e656c2e4a5047

**Comment by HHS81** [comment]
- it's not, I copied the whole file, and so much as I can read it is not done there.
- I combined a translation with rotate animation. I used videos (c182) from youtube as reference.
- according to the videos it is twisted, even Carenado and A2A shows this twist

**Comment by gilbertohasnofb** [comment]
:+1: I will ask onox about the smooth movement then!

**Comment by onox** [comment]
I simply used a `<kinematic>` in `c172p.xml`. See https://github.com/Juanvvc/c172p-detailed/pull/653/files#diff-9eb2c7f8235986e706c0aee4fb47fad6 at the bottom of the page.

**Comment by gilbertohasnofb** [comment]
Thanks, @onox !

**Comment by HHS81** [comment]
@onox Many Thanks! Didn't thought about this, it's a easy one, I will use this soon as I can.

**Comment by gilbertohasnofb** [comment]
We can later apply this to the parking brakes lever as well ( @onox I think the c172p also needs this to be applied for the parking brakes, right?)

**Comment by HHS81** [comment]
Yep, I even think they already did apply this....

**Comment by HHS81** [comment]
Should have been fixed now

**Comment by gilbertohasnofb** [comment]
Really cool animation, Heiko! But if I may be picky, I think the flap isn't really resting in the lowest point of each notch. Try to observe this this: at 10 or 20 degrees, when you lower the flaps you will notice that it first goes a tiny bit down, then right, then down. I think the flap should be resting in the lowest position possible for that notch, so that the movement of lowering the flaps would be only right then down.

**Comment by HHS81** [comment]
Now it should be fixed

**Comment by gilbertohasnofb** [comment]
Strange, retracting the flaps is perfect now, but extending is still a bit strange, there is just a tiny bit of downwards movement before the lateral movement.

**Comment by HHS81** [comment]
and now?

**Comment by gilbertohasnofb** [comment]
Still not. Try this: press Shift+A so that the time compression is exactly at 1/8x (lower values make the flap movement go crazy, but this is enough): now try lowering the flaps from 10 to 20 then raising back. See how the movement when lowering is strange (some unwanted movement) while raising is fine? Same for 20 to 30.

**Comment by HHS81** [comment]
I see what you mean, but lower slow motion values (1/16, 1/32, ...) breaks the whole animation. The slower, the more it seems. Andf I guess that's the reason for your strange observation. Bug in FGFS itself, I would say.

**Comment by gilbertohasnofb** [comment]
No Heiko, I can observe that without any slow motion, but the point is that at 1/8 you can observe better. But at 1x this issue is there!

**Comment by gilbertohasnofb** [comment]
The slow motion tip was just to make sure we are understanding each other on what I meant :wink:

**Comment by HHS81** [comment]
according the table, it should not be the case. 
You should observe the same issue on the c172p, since I used the same principle

**Comment by gilbertohasnofb** [comment]
I will test it on the c172p after, but I don't remember seeing any such thing with its flap. But anyway, it's such a minor thing that I'd say we can just leave it as it is.

**Comment by gilbertohasnofb** [comment]
Heiko, the c172p flap lever movement is much smoother and clearer than ours here, but the difference is just so small that maybe we can just leave it as it is. I leave this up to you, so feel free to close this issue if you want to.

**Comment by HHS81** [comment]
I will close it, if the difference is small, I won't spend any time now. Later maybe.....
